config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "home#index"

  get "/instructions", to: "home#instructions", as: :instructions

  get "/winnow", to: "winnow#index", as: :winnow_index
  patch "/winnow", to: "winnow#submit", as: :winnow_submit

  # We set users to user here for prettier and more make-sensy paths
  resources :users, path: "user", only: [:index, :edit, :update], as: :user

  namespace :admin do
    # Add dashboard for your models here
    resources :categories

    get "/claims/export", to: "claims#export", as: :claim_export
    get "/claims/import", to: "claims#import_show", as: :claim_import
    post "/claims/import", to: "claims#import_submit", as: :claim_import_submit

    resources :claims

    resources :users
    resources :roles, only: [:index, :show]
    resources :category_suggestions do
      patch :approve, as: "approve"
      patch :reject, as: "reject"
      patch :assign_similar_category, as: "assign_similar_category"
    end

    root to: "categories#index" # <--- Root route
  end
end

app/controllers/winnow_controller.rb
class WinnowController < ApplicationController
  before_action :authenticate_user!
  before_action :verify_winnowable_claim, only: [:index]
  before_action :verify_claim, except: [:index]

  def index
    # We only want categories not already assigned to the claim
    @categories = Category.all.order("name ASC") - @claim.categories
    turbolinks_animate "slideInRight"
  end

  def submit
    category_ids = split_submitted_array(claim_params[:categories])
    @categories = category_ids.map do |id|
      Category.find(id)
    end

    @claim.update!({ categories: @categories, checked: true })

    category_suggestions = split_submitted_array(claim_params[:suggestions])
    @category_suggestions = category_suggestions.map do |name|
      CategorySuggestion.create!({ name: name, user: current_user, claim: @claim })
    end

    redirect_to winnow_index_url
  end

private

  def verify_claim
    @claim = Claim.find(claim_params[:id])
  rescue ActiveRecord::RecordNotFound
    render file: "#{Rails.root}/public/404.html", layout: false, status: :not_found
  end

  def verify_winnowable_claim
    @claim = winnowable_claim
    if @claim.nil?
      redirect_to root_path, flash: { notice: "Looks like there are no claims to winnow. Go do something else fun!" }
    end
  end

  def claim_params
    params.require(:claim).permit(:id, :categories, :suggestions)
  end

  def split_submitted_array(id_string)
    seperator = ":::"
    id_string.split(seperator)
  end

  # Choose and return a claim that we want the user to winnow. (This could get interesting with
  # locks and such so it's a separate method.)
  def winnowable_claim
    claim = Claim.where(checked: false).order("RANDOM()").first
    claim
  end
end

app/helpers/winnow_helper.rb
module WinnowHelper
end

app/views/winnow/index.html.erb
 <%= javascript_pack_tag 'categories' %>

<div class="winnow-container">
  <div class="card winnow-content border-info">
  <div class="card-header">
    Categorize Claims
  </div>
  <div class="card-body">
    <div class="diminutive-title">Claim:</div>
    <p class="card-text"><%= @claim.statement %></p>
    <hr>
    <div class="row">
      <div class="col-sm">
        <div class="row">
          <div class="col-sm diminutive-title">Speaker:</div>
          <div class="col-sm additional-info"><%= @claim.speaker_name %> — <%= @claim.speaker_title %></div>
        </div>
      </div>
      <div class="col-sm">
        <div class="row">
          <div class="col-sm diminutive-title">Date:</div>
          <div class="col-sm additional-info"><%= @claim.date %></div>
        </div>
      </div>
      <div class="col-sm">
        <div class="row">
          <div class="col-sm diminutive-title">Publication:</div>
          <div class="col-sm additional-info"><%= @claim.publisher_name %></div>
        </div>
      </div>
    </div>
    <hr>
    <%= form_with path: winnow_submit_path, method: :patch do %>
    <%= hidden_field(:claim, :id) %>
    <div id="categories" data-categories="<%= @categories.to_json %>" data-assigned-categories="<%= @claim.categories.to_json %>"></div>
    <hr>
      <%= link_to "Skip", winnow_index_url, class: "btn btn-outline-secondary submit", style: "float: left" %>
      <button type="submit" class="btn btn-outline-info submit">Save</button>
    <% end %>
  </div>
</div>
</div>