config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "home#index"

  get "/instructions", to: "home#instructions", as: :instructions

  get "/winnow", to: "winnow#index", as: :winnow_index
  patch "/winnow", to: "winnow#submit", as: :winnow_submit

  # We set users to user here for prettier and more make-sensy paths
  resources :users, path: "user", only: [:index, :edit, :update], as: :user

  namespace :admin do
    # Add dashboard for your models here
    resources :categories

    get "/claims/export", to: "claims#export", as: :claim_export
    get "/claims/import", to: "claims#import_show", as: :claim_import
    post "/claims/import", to: "claims#import_submit", as: :claim_import_submit

    resources :claims

    resources :users
    resources :roles, only: [:index, :show]
    resources :category_suggestions do
      patch :approve, as: "approve"
      patch :reject, as: "reject"
      patch :assign_similar_category, as: "assign_similar_category"
    end

    root to: "categories#index" # <--- Root route
  end
end

app/views/shared/_footer.html.erb
<footer class="footer mt-auto py-3 bg-light" data-turbolinks-animate-persist="true">
  <div class="container d-flex justify-content-between">
    <span class="text-muted">A product of the <a href="https://www.reporterslab.org">Duke Reporters' Lab</a></span>
    <span class="text-muted">Created by <a href="https://www.twitter.com/cguess">@cguess</a> | <a href="https://www.github.com/techandcheck/caucus">Github</a></span>
  </div>
</footer>

app/views/shared/_messages.html.erb
<% if flash[:alert] %>
  <div class="alert alert-dismissible alert-danger" role="alert">
    <strong>Error:</strong> <%= flash[:alert].html_safe %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if flash[:error] %>
  <div class="alert alert-dismissible alert-danger" role="alert">
    <strong>Error:</strong> <%= flash[:error].html_safe %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if flash[:success] %>
  <div class="alert alert-dismissible alert-success" role="alert">
    <strong>Success:</strong> <%= flash[:success].html_safe %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if flash[:notice] %>
  <div class="alert alert-dismissible alert-info" role="alert">
    <%= flash[:notice].html_safe %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navigation_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary justify-content-between" data-turbolinks-animate-persist="true">
  <a class="navbar-brand" href="#"><i class="fas fa-sitemap"></i> Caucus</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarToggler" style="justify-content: right;">
    <% if user_signed_in? %>

    <% if current_user.has_role?(:admin) %>
    <div class="navbar-nav mr-1">
      <%= link_to "Admin", admin_categories_path, class: "nav-link" %>
    </div>
    <% end %>

    <div class="navbar-nav mr-1">
      <%= link_to("Instructions", instructions_path, class: "nav-link") %>
    </div>


    <div class="navbar-nav dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= image_tag current_user.avatar.variant(resize_to_limit: [25, 25]) if current_user.avatar.attached? %>
        <%= current_user.email %>
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <%= link_to "Profile", user_index_path(current_user), class: "dropdown-item" %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </div>
    </div>
    <% else %>
    <div class="navbar-nav">
      <%= link_to("Login", new_user_session_path, class: "nav-link") %>
    </div>
    <% end %>
  </div>
</nav>